name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle
      - run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: art-forwarder-debug
          path: app/build/outputs/apk/debug/app-debug.apk
